### ISSUE TITLE
Example 08 `get-spots` is not defined

### ISSUE THREAD

**Issue by dpsutton** [Clojure2D/clojure2d#1]
Was looking through the examples and number 8 appears to be broken. Apparently, `get-spots` seems to no longer exist. I greped through the project and can find no reference of it?

**Comment by tsulej** [comment]
Ok... I changed name to 'make-spots' (the same with get-noise -> make-noise). Will update soon. Thx!

**Comment by tsulej** [comment]
still something is wrong with overlayes

**Comment by tsulej** [comment]
should work now
