### ISSUE TITLE
box and gaussian blurs should operate on doubles

### ISSUE THREAD

**Issue by genmeblog** [Clojure2D/clojure2d#11]
Current implementation is based on ints, that creates "ghosting" issue when blur is applied iteratively.

**Comment by genmeblog** [comment]
Actually there was an issue with rounding. Fixed.

**Comment by adicirstei** [comment]
Is it updated on clojars?

**Comment by genmeblog** [comment]
not yet

**Comment by genmeblog** [comment]
updated, latest snapshot
