### ISSUE TITLE
show-window without window-name doesn't draw

### ISSUE THREAD

**Issue by jdf-id-au** [Clojure2D/clojure2d#20]
Thanks for this brilliant project.

I was surprised, when I ignored the docstring and called [`(show-window canvas)`](https://github.com/Clojure2D/clojure2d/blob/master/src/clojure2d/core.clj#L2388) without a window-name, that it did display the window (including taking account of the canvas dimensions) but didn't draw in it.

I think it might be something to do with the 1-arity of `show-window` somehow destructuring a `Canvas`, but I can't quite nail it down for a PR.

Everything worked when I passed a window-name 😀

**Comment by genmeblog** [comment]
Hi there! Thanks for kind words.

Indeed, `(show-window canvas)` will not work. At some point of development I decided to switch to a map for 1-arity case. The main reason was the high number of function arguments.

This will work:

```clojure
(def canvas (c2d/canvas 800 800))
(c2d/with-canvas-> canvas
  (c2d/set-background 0)
  (c2d/line 10 10 790 790))
(c2d/show-window {:canvas canvas}) ;; 1-arity accepts map
```

**Comment by genmeblog** [comment]
I can add some validation and if input is a Canvas object it will accept this. It's kind of hack I try to avoid usually, but maybe it's ok here.
