### ISSUE TITLE
Vars differing only in case cause problems on case-insensitive filesystems

### ISSUE THREAD

**Issue by emlyn** [Clojure2D/clojure2d#21]
Having two vars that differ only in case causes issues when building a jar on case insensitive file systems, since one class file will overwrite the other. There are two pairs of names causing issues, both in the `clojure2d.color` namespace:
`to-lch` / `to-LCH`
`from-lch` / `from-LCH`
I'd be happy to open a PR if you can suggest a suitable new name for one out of each pair of vars.

**Comment by genmeblog** [comment]
Thanks! Didn't know it could be an issue (Windows?).

Let's change `to-lch` and `from-lch` to (maybe) `to-luma-color-hue` and `from-luma-color-hue` ?
Any other ideas?

PR welcome (it would be great to change also Clerk notebook).

**Comment by emlyn** [comment]
It's actually MacOS, which (depending on the filesystem used) is case preserving, but not case sensitive when accessing/overwriting files. But I think this could also be an issue on Windows.

Those names sound fine to me, I can't think of anything better. I'll start a PR with the change.

**Comment by genmeblog** [comment]
Landed on Clojars
