### ISSUE TITLE
Add support and write example for hidpi screens

### ISSUE THREAD

**Issue by jedahan** [Clojure2D/clojure2d#5]
I ported a quil sketch to clojure2d, and noticed the fonts are a lot fuzzier/hard to read:

### quil
![quil](https://user-images.githubusercontent.com/32407/34342833-9b25ff3c-e98a-11e7-8697-d3766ef36124.png)

### clojure2d
![clojure2d](https://user-images.githubusercontent.com/32407/34342832-9b1abdac-e98a-11e7-81e3-5e76e6c41c62.png)

Wondering how to make it sharper / render at 2x the resolution.

Source is https://github.com/jedahan/calendar/blob/clojure2d/src/calendar.clj

**Comment by jedahan** [comment]
I tried with canvas width and height 2x the window width and height, but now the fonts are incorrect size...

**Comment by tsulej** [comment]
I checked processing implementation of pixelDensity() function. It does the following:
- creates canvas twice bigger
- calls scale(pixelDensity) to have proper virtual size of canvas

You can make the same. Scaling (interpolation) with :high (or :highest) rendering hints is bicubic.

**Comment by tsulej** [comment]
trying to figure out why result is uglier in clojure2d...

**Comment by jedahan** [comment]
@tsulej I got very close to the same quality with https://github.com/jedahan/calendar  - check it out, I think rendering at 2x, setting font sizes to 2x, and then window to '1x' looks a lot sharper

**Comment by tsulej** [comment]
Found a bug related to jframe/awt.canvas creation... nasty. Size of jframe panel was 10pixels bigger than expected. That's why everything wasn't sharp. Everything was scaled up. Today's snapshot fix it.
